# Generated by Django 2.2 on 2021-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210323_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='due_date',
            field=models.DateField(default=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=False, max_length=80),
        ),
    ]
