# Generated by Django 2.2 on 2021-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210323_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(max_length=80),
        ),
        migrations.AlterField(
            model_name='class',
            name='due_date',
            field=models.DateField(max_length=80),
        ),
    ]
