# Generated by Django 2.2 on 2021-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210323_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateField(default=False),
        ),
    ]
