# Generated by Django 2.2 on 2021-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210323_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.CharField(max_length=80),
        ),
    ]
