# Generated by Django 2.2 on 2021-03-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210323_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='due_date',
            field=models.DateField(default=True),
        ),
    ]
