# Generated by Django 2.2 on 2021-03-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210323_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
