# Generated by Django 2.2 on 2021-03-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210323_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(default='False', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateField(default='False', null=True),
        ),
    ]
