# Generated by Django 2.2 on 2021-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210323_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.CharField(default='False', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.CharField(default='False', max_length=100),
            preserve_default=False,
        ),
    ]
