# Generated by Django 2.2 on 2021-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='collection',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
