# Generated by Django 2.2 on 2021-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
