# Generated by Django 2.2 on 2021-04-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='due_date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
