# Generated by Django 2.2 on 2021-03-23 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField(max_length=80)),
                ('completed', models.BooleanField(default=False)),
                ('min_hours', models.PositiveIntegerField()),
                ('max_hours', models.PositiveIntegerField()),
                ('priority', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classes', to='log_reg.User')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(max_length=80)),
                ('completed', models.BooleanField(default=False)),
                ('min_hours', models.PositiveIntegerField()),
                ('max_hours', models.PositiveIntegerField()),
                ('priority', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owns_assignments', to='log_reg.Class')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='log_reg.User')),
            ],
        ),
    ]
