# Generated by Django 2.2 on 2021-03-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg', '0002_assignment_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='class',
            name='max_hours',
        ),
        migrations.RemoveField(
            model_name='class',
            name='min_hours',
        ),
    ]
